# [jupiter.server.http]
#     port = 9090
# [jupiter.etcdv3.default]
#     endpoints=["127.0.0.1:2379"]
#     secure = false
# [jupiter.registry.wh]
#     configKey="jupiter.etcdv3.default"
#     timeout = "1s"

[jupiter.server.http]
    port = 9392
[jupiter.consul.test]
    endpoints=["192.168.88.206:8500"]
    secure = false
[jupiter.registry.test]
    configKey="jupiter.consul.test"
